site_name: Linux Labs
theme:
  name: readthedocs
  language: en
  features:
    - navigation.top
    - search.highlight
    - content.code.annotate

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - tables
  - footnotes
  - def_list
  - attr_list

# pip install mkdocs-awesome-pages-plugin
